### ISSUE TITLE
Export Sass variable values

### ISSUE THREAD

**Issue by styu** [styu/postcss-typesafe-css-modules#23]
CSS modules has an `:export` syntax that allows for exporting Sass variables for use in JavaScript (https://github.com/css-modules/icss?tab=readme-ov-file#export). Ideally these can be imported in a typesafe way into TypeScript files as well. Since information about what is exported is part of the JSON generated by postcss-modules, it shouldn’t be too hard to also generate types and JS values for them as well. Below are some design considerations:

### Use `string` for all types or infer based on values

Sass variables are basically untyped, so the easy thing to do would be to treat everything as string. However, I could foresee wanting numeric pixel values shared between Sass and TypeScript, so we could try and intelligently detect if a value is numeric and type it as such instead. Else, use string for everything else.

### Naming exported variables

Right now, CSS module class names are exported from the file like so:

```js
// header.module.scss.js (auto generated)
export const header = "header__46djqiqp";
```

Suppose the following variable is exported from a Sass module file:

```css
$page-width: 850px;
:export {
  pageWidth: $page-width;
}
```

I can see a couple options for exporting the variable to avoid conflicts with exported classes:

#### Option 1: Nest under separate objects

Instead of exporting class names at the top level, nest them under a dedicated `classes` object. Variables are then nested under a dedicated `variables` object:

```js
// hello.module.scss.js
export const classes = {
  header: "header__46djqiqp",
}
export const variables = {
  pageWidth: "850px",
};
```

```ts
import { classes, variables } from "./hello.module.scss";

export const HelloWorld: React.FC = () => {
    const pageSize = variables.pageWidth;
    return <header className={classes.header}>Hello World</header>;
};
```

Pros:
- Extensible in case there are other “types” of values that we want to export in the future, since new objects can just be added

Cons:
- A little more verbose to use and import (vs just `import * as css`)
- Technically less efficient to store in an object instead of flat variables 

#### Option 2: Prefix exported variable names with `$`

According to the [CSS spec](https://www.w3.org/TR/CSS21/syndata.html#characters), `$` is not a valid character to use in a CSS class name, so there’s no possibility of conflicting with the existing exported class names in our generated JS file:

```js
// header.module.scss.js (auto generated)
export const header = "header__46djqiqp";
export const $pageWidth = "850px”;
```

```ts
import * as css from "./hello.module.scss";

export const HelloWorld: React.FC = () => {
    const pageSize = css.$pageWidth;
    return <header className={css.header}>Hello World</header>;
};
```

Pros:
- More compact import syntax
- Variable naming mirrors what you use in Sass

Cons:
- Less extensible, if there’s another type we want to export we may have to think of a new clever deconfliction scheme

#### Option 3: Export everything as variables and throw when there are conflicts

This means that in the following scenario, the build will fail:

```css
$page: 850px;
:export {
  page: $page;
}

.page {
  width: $page;
}
```

Pros:
- Simple to implement and no possibility of conflicts

Cons:
- No distinction when consuming the exports between what is a CSS class name or an exported variable

**Comment by walkerburgin** [comment]
What if you just failed the build if there's a conflict with named exports? 

I would stick with just exposing strings to avoid ending up in a YAML-esque situation 😄. If the consumer wants to parse a string as a number, that's easy enough for them to do 🤷‍♂️

**Comment by walkerburgin** [comment]
I wouldn't make naming decisions based on Sass's conventions. You should be able to use `:export` regardless of which pre-processor you're using -- or even whether you're using a pre-processor at all

**Comment by styu** [comment]
> I would stick with just exposing strings to avoid ending up in a YAML-esque situation 😄. If the consumer wants to parse a string as a number, that's easy enough for them to do 🤷‍♂️

Yeah, I lean towards just exposing as strings as well to avoid being too magic.

> What if you just failed the build if there's a conflict with named exports?

I thought about this as well. I have a slight preference towards being able to distinguish whether you're using a class name or a variable in the TypeScript file though 🤔

**Comment by invliD** [comment]
I agree with everything here. Option 3 is also what I'd bias towards, mostly because that behavior is what I would expect as a consumer.

> I have a slight preference towards being able to distinguish whether you're using a class name or a variable

I _feel_ like that shouldn't be too much of an issue. This is the behavior everywhere—if a TS file exports two string constants that represent completely different things, there is also no compile-time check that guards against using the wrong one.
